### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, debug.log]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "IngeNUity 2017"
keywords:    "Ingenuity, Techno Fest, NIIT University, Fest, Cultural-fest"
description: "Ingenuity Techo-Cultural Fest"
bg-img: ""

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#FAFAFA'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

## events collection for events
collections:
  events:
    output: true
    permalink: /:path

kramdown:
  auto_ids:  false

