### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, debug.log]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#FAFAFA'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

## events collection for events
collections:
  events:
    output: true
    permalink: /:path
  dance:
    output: true
    permalink: /:path
  music:
    output: true
    permalink: /:path
  literary:
    output: true
    permalink: /:path
  drama:
    output: true
    permalink: /:path
  tech:
    output: true
    permalink: /:path
  fashion:
    output: true
    permalink: /:path
  members:
  homepages:

kramdown:
  auto_ids:  false

gems:
  - jekyll-sitemap